@Authentication.Api_HostAddress = https://localhost:7258

###

POST {{Authentication.Api_HostAddress}}/api/account/register
Content-Type: application/json

{
  "username" : "Adrian",
  "email" : "adrian@rulerhub.org",
  "password" : "Tor.2024"
}

###

POST {{Authentication.Api_HostAddress}}/api/account/login
Content-Type: application/json

{
  "userName": "Adrian",
  "password": "Tor.2024"
}

###

POST {{Authentication.Api_HostAddress}}/api/account/logout

###
